---
# Source: aws-usea1-qa-qa/templates/gitrepo.yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: cert-manager
  annotations:
    field.cattle.io/description: "JetStack Certificate Manager"
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-usea1-qa-qa
    helm.sh/chart: aws-usea1-qa-qa-2.0.188
spec:
  clientSecretName: gitlab-caas-ops
  paths:
  - cert-manager
  repo: https://github.com/khushalchandak17/nginx.git
  revision: dd-cert-manager-label
  targets:
  - clusterSelector: {}
    name: all
