---
# Source: aws-usea1-qa-qa/templates/gitrepo.yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: calico-networkpolicy
  annotations:
    field.cattle.io/description: "Calico (Network Policy Engine)"
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-usea1-qa-qa
    helm.sh/chart: aws-usea1-qa-qa-2.0.188
spec:
  clientSecretName: gitlab-caas-ops
  repo: https://gitlab.industrysoftware.automation.siemens.com/caas-ops/helm-calico-networkpolicy.git
  revision: update
  targets:
  - clusterSelector: {}
    name: all
---
# Source: aws-usea1-qa-qa/templates/gitrepo.yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: cert-manager
  annotations:
    field.cattle.io/description: "JetStack Certificate Manager"
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-usea1-qa-qa
    helm.sh/chart: aws-usea1-qa-qa-2.0.188
spec:
  clientSecretName: gitlab-caas-ops
  paths:
  - cert-manager
  repo: https://gitlab.industrysoftware.automation.siemens.com/caas-ops/helm-external.git
  revision: dd-cert-manager-label
  targets:
  - clusterSelector: {}
    name: all
---
# Source: aws-usea1-qa-qa/templates/gitrepo.yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: cert-manager-issuers
  annotations:
    field.cattle.io/description: "Cert-Manager Cluster Issuers"
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-usea1-qa-qa
    helm.sh/chart: aws-usea1-qa-qa-2.0.188
spec:
  clientSecretName: gitlab-caas-ops
  repo: https://gitlab.industrysoftware.automation.siemens.com/caas-ops/helm-issuers.git
  revision: 1.2.17
  targets:
  - clusterSelector: {}
    name: all
---
# Source: aws-usea1-qa-qa/templates/gitrepo.yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: cluster-autoscaler
  annotations:
    field.cattle.io/description: "Cluster Autoscaler"
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-usea1-qa-qa
    helm.sh/chart: aws-usea1-qa-qa-2.0.188
spec:
  clientSecretName: gitlab-caas-ops
  paths:
  - cluster-autoscaler
  repo: https://gitlab.industrysoftware.automation.siemens.com/caas-ops/helm-external.git
  revision: 1.0.287
  targets:
  - clusterSelector: {}
    name: all
---
# Source: aws-usea1-qa-qa/templates/gitrepo.yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: datadog
  annotations:
    field.cattle.io/description: "Datadog Agent"
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-usea1-qa-qa
    helm.sh/chart: aws-usea1-qa-qa-2.0.188
spec:
  clientSecretName: gitlab-caas-ops
  paths:
  - datadog
  repo: https://gitlab.industrysoftware.automation.siemens.com/caas-ops/helm-external.git
  revision: 1.0.287
  targets:
  - clusterSelector: {}
    name: all
---
# Source: aws-usea1-qa-qa/templates/gitrepo.yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: dnsrecords
  annotations:
    field.cattle.io/description: "DNS records managed by External DNS"
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-usea1-qa-qa
    helm.sh/chart: aws-usea1-qa-qa-2.0.188
spec:
  clientSecretName: gitlab-caas-ops
  repo: https://gitlab.industrysoftware.automation.siemens.com/caas-ops/helm-dnsrecords.git
  revision: 1.0.69
  targets:
  - clusterSelector: {}
    name: all
---
# Source: aws-usea1-qa-qa/templates/gitrepo.yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: ebs-csi-driver
  annotations:
    field.cattle.io/description: "EBS CSI Driver"
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-usea1-qa-qa
    helm.sh/chart: aws-usea1-qa-qa-2.0.188
spec:
  clientSecretName: gitlab-caas-ops
  paths:
  - aws-ebs-csi-driver
  repo: https://gitlab.industrysoftware.automation.siemens.com/caas-ops/helm-external.git
  revision: 1.0.287
  targets:
  - clusterSelector: {}
    name: all
---
# Source: aws-usea1-qa-qa/templates/gitrepo.yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: external-dns
  annotations:
    field.cattle.io/description: "External DNS"
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-usea1-qa-qa
    helm.sh/chart: aws-usea1-qa-qa-2.0.188
spec:
  clientSecretName: gitlab-caas-ops
  paths:
  - external-dns
  repo: https://gitlab.industrysoftware.automation.siemens.com/caas-ops/helm-external.git
  revision: 1.0.287
  targets:
  - clusterSelector: {}
    name: all
---
# Source: aws-usea1-qa-qa/templates/gitrepo.yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: ingress-nginx
  annotations:
    field.cattle.io/description: "NginX Ingress Controller"
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-usea1-qa-qa
    helm.sh/chart: aws-usea1-qa-qa-2.0.188
spec:
  clientSecretName: gitlab-caas-ops
  paths:
  - ingress-nginx
  repo: https://gitlab.industrysoftware.automation.siemens.com/caas-ops/helm-external.git
  revision: 1.0.287
  targets:
  - clusterSelector: {}
    name: all
---
# Source: aws-usea1-qa-qa/templates/gitrepo.yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: metrics-server
  annotations:
    field.cattle.io/description: "Metrics Server"
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-usea1-qa-qa
    helm.sh/chart: aws-usea1-qa-qa-2.0.188
spec:
  clientSecretName: gitlab-caas-ops
  paths:
  - metrics-server
  repo: https://gitlab.industrysoftware.automation.siemens.com/caas-ops/helm-external.git
  revision: 1.0.287
  targets:
  - clusterSelector: {}
    name: all
---
# Source: aws-usea1-qa-qa/templates/gitrepo.yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: opa-library
  annotations:
    field.cattle.io/description: "OPA Library"
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-usea1-qa-qa
    helm.sh/chart: aws-usea1-qa-qa-2.0.188
spec:
  clientSecretName: gitlab-caas-ops
  repo: https://gitlab.industrysoftware.automation.siemens.com/caas-ops/helm-opalibrary.git
  revision: 0.0.22
  targets:
  - clusterSelector: {}
    name: all
---
# Source: aws-usea1-qa-qa/templates/gitrepo.yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: rancher-gatekeeper
  annotations:
    field.cattle.io/description: "Rancher OPA Gatekeeper"
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-usea1-qa-qa
    helm.sh/chart: aws-usea1-qa-qa-2.0.188
spec:
  clientSecretName: gitlab-caas-ops
  paths:
  - rancher-gatekeeper-crd
  - rancher-gatekeeper
  repo: https://gitlab.industrysoftware.automation.siemens.com/caas-ops/helm-external.git
  revision: 1.0.287
  targets:
  - clusterSelector: {}
    name: all
---
# Source: aws-usea1-qa-qa/templates/gitrepo.yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: siemens-opa
  annotations:
    field.cattle.io/description: "Siemens OPA Constraints"
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-usea1-qa-qa
    helm.sh/chart: aws-usea1-qa-qa-2.0.188
spec:
  clientSecretName: gitlab-caas-ops
  repo: https://gitlab.industrysoftware.automation.siemens.com/caas-ops/helm-opa.git
  revision: 1.0.37
  targets:
  - clusterSelector: {}
    name: all
---
# Source: aws-usea1-qa-qa/templates/gitrepo.yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: sealed-secrets-controller
  annotations:
    field.cattle.io/description: "Bitnami Sealed Secrets controller"
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-usea1-qa-qa
    helm.sh/chart: aws-usea1-qa-qa-2.0.188
spec:
  clientSecretName: gitlab-caas-ops
  paths:
  - sealed-secrets
  repo: https://gitlab.industrysoftware.automation.siemens.com/caas-ops/helm-external.git
  revision: 1.0.287
  targets:
  - clusterSelector: {}
    name: all
---
# Source: aws-usea1-qa-qa/templates/gitrepo.yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: secrets
  annotations:
    field.cattle.io/description: "KaaS SealedSecrets"
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-usea1-qa-qa
    helm.sh/chart: aws-usea1-qa-qa-2.0.188
spec:
  clientSecretName: gitlab-caas-ops
  repo: https://gitlab.industrysoftware.automation.siemens.com/caas-ops/helm-secrets.git
  revision: 1.1.77
  targets:
  - clusterSelector: {}
    name: all
---
# Source: aws-usea1-qa-qa/templates/gitrepo.yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: snapshot-controller
  annotations:
    field.cattle.io/description: "CSI Snapshot Controller"
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-usea1-qa-qa
    helm.sh/chart: aws-usea1-qa-qa-2.0.188
spec:
  clientSecretName: gitlab-caas-ops
  paths:
  - snapshot-controller
  - snapshot-validation-webhook
  repo: https://gitlab.industrysoftware.automation.siemens.com/caas-ops/helm-external.git
  revision: 1.0.287
  targets:
  - clusterSelector: {}
    name: all
---
# Source: aws-usea1-qa-qa/templates/gitrepo.yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: storageclasses
  annotations:
    field.cattle.io/description: "Storage Classes and Volume Snapshot Classes"
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-usea1-qa-qa
    helm.sh/chart: aws-usea1-qa-qa-2.0.188
spec:
  clientSecretName: gitlab-caas-ops
  repo: https://gitlab.industrysoftware.automation.siemens.com/caas-ops/helm-storageclasses.git
  revision: 1.0.26
  targets:
  - clusterSelector: {}
    name: all
---
# Source: aws-usea1-qa-qa/templates/gitrepo.yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: velero
  annotations:
    field.cattle.io/description: "Velero Backups"
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-usea1-qa-qa
    helm.sh/chart: aws-usea1-qa-qa-2.0.188
spec:
  clientSecretName: gitlab-caas-ops
  paths:
  - velero
  repo: https://gitlab.industrysoftware.automation.siemens.com/caas-ops/helm-external.git
  revision: 1.0.287
  targets:
  - clusterSelector: {}
    name: all
---
# Source: aws-usea1-qa-qa/templates/gitrepo.yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: xcr-foundation
  annotations:
    field.cattle.io/description: "XCR Foundation chart"
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-usea1-qa-qa
    helm.sh/chart: aws-usea1-qa-qa-2.0.188
spec:
  branch: master
  clientSecretName: gitlab
  repo: https://gitlab.industrysoftware.automation.siemens.com/chimera/kubernetes/fleet/foundation.git
  targets:
  - clusterSelector: {}
    name: all
---
# Source: aws-usea1-qa-qa/templates/gitrepo.yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: xcr-logging
  annotations:
    field.cattle.io/description: "XCR Logging stack for rancher cluster"
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-usea1-qa-qa
    helm.sh/chart: aws-usea1-qa-qa-2.0.188
spec:
  branch: main
  clientSecretName: gitlab
  paths:
  - logging-crd
  - logging-chart
  - ns-logging-obj
  repo: https://gitlab.industrysoftware.automation.siemens.com/chimera/kubernetes/fleet/logging.git
  targets:
  - clusterSelector: {}
    name: all
---
# Source: aws-usea1-qa-qa/templates/gitrepo.yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: xcr-loki
  annotations:
    field.cattle.io/description: "XCR Loki stack for rancher cluster"
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-usea1-qa-qa
    helm.sh/chart: aws-usea1-qa-qa-2.0.188
spec:
  branch: master
  clientSecretName: gitlab
  paths:
  - loki
  - loki-canary
  repo: https://gitlab.industrysoftware.automation.siemens.com/chimera/kubernetes/fleet/loki.git
  targets:
  - clusterSelector: {}
    name: all
---
# Source: aws-usea1-qa-qa/templates/gitrepo.yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: xcr-monitoring
  annotations:
    field.cattle.io/description: "XCR Monitoring stack for rancher cluster"
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-usea1-qa-qa
    helm.sh/chart: aws-usea1-qa-qa-2.0.188
spec:
  branch: main
  clientSecretName: gitlab
  paths:
  - monitoring-charts
  - service-account
  - blackbox
  - grafana_resources
  - alertmanager_config
  - grafana_dashboards
  repo: https://gitlab.industrysoftware.automation.siemens.com/chimera/kubernetes/fleet/monitoring.git
  targets:
  - clusterSelector: {}
    name: all
---
# Source: aws-usea1-qa-qa/templates/gitrepo.yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: xcr-vault-secrets-webhook
  annotations:
    field.cattle.io/description: "XCR Banzaicloud vault webhook chart"
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-usea1-qa-qa
    helm.sh/chart: aws-usea1-qa-qa-2.0.188
spec:
  branch: main
  clientSecretName: gitlab
  paths:
  - vault-secrets-webhook-chart
  - banzai-webhook-addons
  repo: https://gitlab.industrysoftware.automation.siemens.com/chimera/kubernetes/fleet/banzaicloud-vault-webhook.git
  targets:
  - clusterSelector: {}
    name: all
---
# Source: aws-usea1-qa-qa/templates/gitrepo.yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: xcr-aqua-kube-enforcer
  annotations:
    field.cattle.io/description: "XCR aqua enforcer charts"
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-usea1-qa-qa
    helm.sh/chart: aws-usea1-qa-qa-2.0.188
spec:
  branch: XCD-2137
  clientSecretName: gitlab
  paths:
  - kube-enforcer
  - kube-enforcer-certs
  repo: https://gitlab.industrysoftware.automation.siemens.com/chimera/kubernetes/fleet/aqua.git
  targets:
  - clusterSelector: {}
    name: all
---
# Source: aws-usea1-qa-qa/templates/gitrepo.yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: xcr-aqua-enforcer
  annotations:
    field.cattle.io/description: "XCR aqua enforcer charts"
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-usea1-qa-qa
    helm.sh/chart: aws-usea1-qa-qa-2.0.188
spec:
  branch: XCD-2137
  clientSecretName: gitlab
  paths:
  - aqua-enforcer
  repo: https://gitlab.industrysoftware.automation.siemens.com/chimera/kubernetes/fleet/aqua.git
  targets:
  - clusterSelector: {}
    name: all
---
# Source: aws-usea1-qa-qa/templates/gitrepo.yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: xcr-argocd-rbac
  annotations:
    field.cattle.io/description: "XCR ArgoCD RBAC chart"
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-usea1-qa-qa
    helm.sh/chart: aws-usea1-qa-qa-2.0.188
spec:
  branch: main
  clientSecretName: gitlab
  paths:
  - argocd-rbac
  repo: https://gitlab.industrysoftware.automation.siemens.com/chimera/kubernetes/fleet/argocd-rbac.git
  targets:
  - clusterSelector: {}
    name: all
---
# Source: aws-usea1-qa-qa/templates/gitrepo.yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: xcr-hnc-qa
  annotations:
    field.cattle.io/description: "hnc"
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-usea1-qa-qa
    helm.sh/chart: aws-usea1-qa-qa-2.0.188
spec:
  branch: main
  clientSecretName: gitlab
  paths:
  - hnc
  - hnc-backup
  - hnc-config-job
  repo: https://gitlab.industrysoftware.automation.siemens.com/chimera/kubernetes/fleet/hnc.git
  targets:
  - clusterSelector: {}
    name: all
---
# Source: aws-usea1-qa-qa/templates/gitrepo.yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: xcr-custom-promrule-testing
  annotations:
    field.cattle.io/description: "promtheus rule testing"
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-usea1-qa-qa
    helm.sh/chart: aws-usea1-qa-qa-2.0.188
spec:
  branch: main
  clientSecretName: gitlab
  repo: https://gitlab.industrysoftware.automation.siemens.com/chimera/kubernetes/fleet/xcr-custom-alerts.git
  targets:
  - clusterSelector: {}
    name: all
---
# Source: aws-usea1-qa-qa/templates/gitrepo.yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: xcr-ovp-app
  annotations:
    field.cattle.io/description: "OVP app for env testing"
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-usea1-qa-qa
    helm.sh/chart: aws-usea1-qa-qa-2.0.188
spec:
  clientSecretName: gitlab
  paths:
  - ovp-app-chart
  - ovp-addons
  repo: https://gitlab.industrysoftware.automation.siemens.com/chimera/kubernetes/fleet/ovp-app.git
  revision: 1.0.32
  targets:
  - clusterSelector: {}
    name: all
---
# Source: aws-usea1-qa-qa/templates/gitrepo.yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: reloader-global
  annotations:
    field.cattle.io/description: "global reloader"
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-usea1-qa-qa
    helm.sh/chart: aws-usea1-qa-qa-2.0.188
spec:
  clientSecretName: gitlab-caas-ops
  paths:
  - reloader-global
  repo: https://gitlab.industrysoftware.automation.siemens.com/caas-ops/helm-external.git
  revision: 1.0.287
  targets:
  - clusterSelector: {}
    name: all
---
# Source: aws-usea1-qa-qa/templates/gitrepo.yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: cloudability
  annotations:
    field.cattle.io/description: "Cloudability metrics-agent"
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-usea1-qa-qa
    helm.sh/chart: aws-usea1-qa-qa-2.0.188
spec:
  clientSecretName: gitlab-caas-ops
  paths:
  - cloudability
  repo: https://gitlab.industrysoftware.automation.siemens.com/caas-ops/helm-external.git
  revision: 1.0.287
  targets:
  - clusterSelector: {}
    name: all
